package crypto

import (
	"testing"
	"time"
)

func TestQuantumRandomGenerator_Initialize(t *testing.T) {
	generator := NewQuantumRandomGenerator()

	err := generator.Initialize()
	if err != nil {
		t.Fatalf("Initialize failed: %v", err)
	}
}

func TestQuantumRandomGenerator_GenerateRandomBytes(t *testing.T) {
	generator := NewQuantumRandomGenerator()
	_ = generator.Initialize()

	testCases := []struct {
		name   string
		length int
	}{
		{"small length", 8},
		{"medium length", 64},
		{"large length", 256},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			bytes, err := generator.GenerateRandomBytes(tc.length)
			if err != nil {
				t.Fatalf("GenerateRandomBytes failed: %v", err)
			}

			if len(bytes) != tc.length {
				t.Errorf("Expected %d bytes, got %d", tc.length, len(bytes))
			}

			allZeros := true
			for _, b := range bytes {
				if b != 0 {
					allZeros = false
					break
				}
			}
			if allZeros {
				t.Error("Generated bytes should not all be zero")
			}
		})
	}
}

func TestQuantumRandomGenerator_GenerateQuantumRandomString(t *testing.T) {
	generator := NewQuantumRandomGenerator()
	_ = generator.Initialize()

	config := &QuantumCaptchaConfig{
		Length:           6,
		CharacterSet:   "ABCDEFGHJKLMNPQRSTUVWXYZ23456789",
		NoiseLevel:       0.3,
		AntiAI:           true,
		QuantumEnhanced: true,
		Unpredictability: 0.95,
	}

	challenge, err := generator.GenerateQuantumRandomString(config)
	if err != nil {
		t.Fatalf("GenerateQuantumRandomString failed: %v", err)
	}

	if len(challenge.Characters) != 6 {
		t.Errorf("Expected 6 characters, got %d", len(challenge.Characters))
	}

	if len(challenge.NoisePattern) != 6 {
		t.Errorf("Expected 6 noise patterns, got %d", len(challenge.NoisePattern))
	}

	if challenge.Entropy <= 0 {
		t.Error("Entropy should be positive")
	}

	if challenge.QuantumBits <= 0 {
		t.Error("QuantumBits should be positive")
	}

	if challenge.Signature == "" {
		t.Error("Signature should not be empty")
	}

	if !challenge.PredictionResistant {
		t.Error("Challenge should be prediction resistant")
	}
}

func TestQuantumRandomGenerator_GenerateQuantumRandomString_DefaultConfig(t *testing.T) {
	generator := NewQuantumRandomGenerator()
	_ = generator.Initialize()

	challenge, err := generator.GenerateQuantumRandomString(nil)
	if err != nil {
		t.Fatalf("GenerateQuantumRandomString with nil config failed: %v", err)
	}

	if len(challenge.Characters) != 6 {
		t.Errorf("Expected default length 6, got %d", len(challenge.Characters))
	}
}

func TestQuantumRandomGenerator_GenerateQuantumRandomString_LengthBounds(t *testing.T) {
	generator := NewQuantumRandomGenerator()
	_ = generator.Initialize()

	testCases := []struct {
		name          string
		inputLength   int
		expectedMin   int
		expectedMax   int
	}{
		{"too short", 2, 4, 4},
		{"too long", 20, 16, 16},
		{"valid short", 6, 6, 6},
		{"valid long", 12, 12, 12},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			config := &QuantumCaptchaConfig{Length: tc.inputLength}
			challenge, err := generator.GenerateQuantumRandomString(config)
			if err != nil {
				t.Fatalf("GenerateQuantumRandomString failed: %v", err)
			}

			if len(challenge.Characters) < tc.expectedMin || len(challenge.Characters) > tc.expectedMax {
				t.Errorf("Expected length between %d and %d, got %d", tc.expectedMin, tc.expectedMax, len(challenge.Characters))
			}
		})
	}
}

func TestQuantumRandomGenerator_VerifyQuantumChallenge_Success(t *testing.T) {
	generator := NewQuantumRandomGenerator()
	_ = generator.Initialize()

	config := &QuantumCaptchaConfig{
		Length:           4,
		CharacterSet:   "ABCDEF",
		QuantumEnhanced: true,
	}

	challenge, err := generator.GenerateQuantumRandomString(config)
	if err != nil {
		t.Fatalf("GenerateQuantumRandomString failed: %v", err)
	}

	userInput := string(challenge.Characters)

	success, matchRatio, err := generator.VerifyQuantumChallenge(challenge, userInput)
	if err != nil {
		t.Fatalf("VerifyQuantumChallenge failed: %v", err)
	}

	if !success {
		t.Error("Verification should succeed with correct input")
	}

	if matchRatio < 0.8 {
		t.Errorf("Match ratio should be >= 0.8, got %.2f", matchRatio)
	}
}

func TestQuantumRandomGenerator_VerifyQuantumChallenge_Failure(t *testing.T) {
	generator := NewQuantumRandomGenerator()
	_ = generator.Initialize()

	config := &QuantumCaptchaConfig{
		Length:           4,
		CharacterSet:   "ABCDEF",
		QuantumEnhanced: true,
	}

	challenge, _ := generator.GenerateQuantumRandomString(config)

	userInput := "XXXX"

	success, _, _ := generator.VerifyQuantumChallenge(challenge, userInput)

	if success {
		t.Error("Verification should fail with wrong input")
	}
}

func TestQuantumRandomGenerator_VerifyQuantumChallenge_LengthMismatch(t *testing.T) {
	generator := NewQuantumRandomGenerator()
	_ = generator.Initialize()

	config := &QuantumCaptchaConfig{
		Length:           4,
		CharacterSet:   "ABCDEF",
	}

	challenge, _ := generator.GenerateQuantumRandomString(config)

	userInput := "ABC"

	success, _, err := generator.VerifyQuantumChallenge(challenge, userInput)

	if err == nil {
		t.Error("Should return error for length mismatch")
	}
	if success {
		t.Error("Verification should fail with length mismatch")
	}
}

func TestQuantumRandomGenerator_GenerateAntiAIPattern(t *testing.T) {
	generator := NewQuantumRandomGenerator()
	_ = generator.Initialize()

	pattern, err := generator.GenerateAntiAIPattern(100)
	if err != nil {
		t.Fatalf("GenerateAntiAIPattern failed: %v", err)
	}

	if len(pattern) != 100 {
		t.Errorf("Expected pattern length 100, got %d", len(pattern))
	}

	allZeros := true
	for _, b := range pattern {
		if b != 0 {
			allZeros = false
			break
		}
	}
	if allZeros {
		t.Error("Generated pattern should not all be zero")
	}
}

func TestQuantumRandomGenerator_GenerateVisualNoisePattern(t *testing.T) {
	generator := NewQuantumRandomGenerator()
	_ = generator.Initialize()

	pattern, err := generator.GenerateVisualNoisePattern(100, 100)
	if err != nil {
		t.Fatalf("GenerateVisualNoisePattern failed: %v", err)
	}

	if len(pattern) != 100 {
		t.Errorf("Expected 100 rows, got %d", len(pattern))
	}

	if len(pattern[0]) != 100 {
		t.Errorf("Expected 100 columns, got %d", len(pattern[0]))
	}

	for y := 0; y < 100; y++ {
		for x := 0; x < 100; x++ {
			if pattern[y][x] < -1 || pattern[y][x] > 1 {
				t.Errorf("Noise value at [%d,%d] out of range [-1,1]: %.3f", y, x, pattern[y][x])
			}
		}
	}
}

func TestQuantumRandomGenerator_GetEntropyPoolStatus(t *testing.T) {
	generator := NewQuantumRandomGenerator()
	_ = generator.Initialize()

	status := generator.GetEntropyPoolStatus()

	if status["pool_size"] != 256 {
		t.Errorf("Expected pool_size 256, got %v", status["pool_size"])
	}

	if status["last_refresh"] == nil {
		t.Error("last_refresh should not be nil")
	}

	if status["quantum_source"] == nil {
		t.Error("quantum_source should not be nil")
	}
}

func TestQuantumRandomGenerator_EstimateBreakingComplexity(t *testing.T) {
	generator := NewQuantumRandomGenerator()
	_ = generator.Initialize()

	challenge := &QuantumChallenge{
		Entropy:              32.0,
		QuantumBits:          6,
		PredictionResistant:  true,
	}

	complexity := generator.EstimateBreakingComplexity(challenge)

	if complexity < 1e9 {
		t.Errorf("Complexity should be >= 1e9, got %.2e", complexity)
	}
}

func TestQuantumRandomGenerator_GenerateSignature(t *testing.T) {
	generator := NewQuantumRandomGenerator()
	_ = generator.Initialize()

	characters := []rune{'A', 'B', 'C', 'D'}

	signature := generator.generateSignature(characters)

	if signature == "" {
		t.Error("Signature should not be empty")
	}

	signature2 := generator.generateSignature(characters)

	if signature == signature2 {
		t.Error("Different signatures should be generated for same input")
	}
}

func TestBoxMullerTransform(t *testing.T) {
	samples := make([]float64, 1000)

	for i := 0; i < 1000; i++ {
		samples[i] = boxMullerTransform()
	}

	sum := 0.0
	for _, s := range samples {
		sum += s
	}
	mean := sum / float64(len(samples))

	if mean < -0.2 || mean > 0.2 {
		t.Errorf("Mean should be close to 0, got %.3f", mean)
	}
}

func TestRandFloat64(t *testing.T) {
	samples := make([]float64, 100)

	for i := 0; i < 100; i++ {
		samples[i] = randFloat64()
	}

	for _, s := range samples {
		if s < 0 || s >= 1 {
			t.Errorf("randFloat64 should return value in [0,1), got %.3f", s)
		}
	}

	allSame := true
	for i := 1; i < len(samples); i++ {
		if samples[i] != samples[0] {
			allSame = false
			break
		}
	}
	if allSame {
		t.Error("randFloat64 should not return the same value every time")
	}
}

func TestCalculateStringSimilarity(t *testing.T) {
	generator := NewQuantumRandomGenerator()

	testCases := []struct {
		s1       string
		s2       string
		minMatch float64
		maxMatch float64
	}{
		{"same", "same", 0.9, 1.0},
		{"abc", "abc", 0.9, 1.0},
		{"abc", "xyz", 0.0, 0.2},
		{"", "", 1.0, 1.0},
	}

	for _, tc := range testCases {
		t.Run(tc.s1+"_"+tc.s2, func(t *testing.T) {
			result := generator.calculateStringSimilarity(tc.s1, tc.s2)
			if result < tc.minMatch || result > tc.maxMatch {
				t.Errorf("Expected similarity between %.2f and %.2f, got %.2f", tc.minMatch, tc.maxMatch, result)
			}
		})
	}
}

func TestQuantumRandomGenerator_RefreshEntropyPool(t *testing.T) {
	generator := NewQuantumRandomGenerator()

	err := generator.refreshEntropyPool()
	if err != nil {
		t.Fatalf("refreshEntropyPool failed: %v", err)
	}

	if generator.lastRefreshTime.IsZero() {
		t.Error("lastRefreshTime should be updated after refresh")
	}
}

func TestQuantumRandomGenerator_GenerateQuantumNoise(t *testing.T) {
	generator := NewQuantumRandomGenerator()

	noise := generator.generateQuantumNoise(100)

	if len(noise) != 100 {
		t.Errorf("Expected 100 noise bytes, got %d", len(noise))
	}

	allZeros := true
	for _, n := range noise {
		if n != 0 {
			allZeros = false
			break
		}
	}
	if allZeros {
		t.Error("Quantum noise should not all be zero")
	}
}

func TestQuantumRandomGenerator_GenerateThermalNoise(t *testing.T) {
	generator := NewQuantumRandomGenerator()

	noise := generator.generateThermalNoise(100)

	if len(noise) != 100 {
		t.Errorf("Expected 100 noise bytes, got %d", len(noise))
	}

	allZeros := true
	for _, n := range noise {
		if n != 0 {
			allZeros = false
			break
		}
	}
	if allZeros {
		t.Error("Thermal noise should not all be zero")
	}
}

func TestQuantumRandomGenerator_SampleQuantumBit(t *testing.T) {
	generator := NewQuantumRandomGenerator()

	samples := make([]byte, 1000)
	for i := 0; i < 1000; i++ {
		samples[i] = generator.sampleQuantumBit()
	}

	ones := 0
	for _, s := range samples {
		if s == 0xFF {
			ones++
		}
	}

	onesRatio := float64(ones) / float64(len(samples))

	if onesRatio < 0.3 || onesRatio > 0.7 {
		t.Errorf("Quantum bit distribution should be roughly 50/50, got %.2f%% ones", onesRatio*100)
	}
}

func BenchmarkQuantumRandomGenerator_GenerateRandomBytes(b *testing.B) {
	generator := NewQuantumRandomGenerator()
	_ = generator.Initialize()

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, _ = generator.GenerateRandomBytes(64)
	}
}

func BenchmarkQuantumRandomGenerator_GenerateQuantumRandomString(b *testing.B) {
	generator := NewQuantumRandomGenerator()
	_ = generator.Initialize()

	config := &QuantumCaptchaConfig{
		Length:           8,
		CharacterSet:   "ABCDEFGHJKLMNPQRSTUVWXYZ23456789",
		QuantumEnhanced: true,
	}

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, _ = generator.GenerateQuantumRandomString(config)
	}
}

func BenchmarkQuantumRandomGenerator_GenerateVisualNoisePattern(b *testing.B) {
	generator := NewQuantumRandomGenerator()
	_ = generator.Initialize()

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, _ = generator.GenerateVisualNoisePattern(100, 100)
	}
}
