package metrics

import (
	"log"
	"net/http"
	"strconv"
	"sync"
	"sync/atomic"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/hjtpx/hjtpx/pkg/database"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

var (
	startTime = time.Now()

	requestCount uint64
	successCount uint64
	failureCount uint64
	requestMu    sync.RWMutex
)

func init() {
	go metricsCollector()
}

func metricsCollector() {
	ticker := time.NewTicker(1 * time.Minute)
	defer ticker.Stop()
	for range ticker.C {
		if atomic.LoadUint64(&requestCount) > 0 {
			atomic.StoreUint64(&requestCount, atomic.LoadUint64(&requestCount)/2)
		}
	}
}

func IncrementRequestCount() {
	atomic.AddUint64(&requestCount, 1)
}

func IncrementSuccessCount() {
	atomic.AddUint64(&successCount, 1)
}

func IncrementFailureCount() {
	atomic.AddUint64(&failureCount, 1)
}

func GetRequestCount() uint64 {
	return atomic.LoadUint64(&requestCount)
}

func GetSuccessCount() uint64 {
	return atomic.LoadUint64(&successCount)
}

func GetFailureCount() uint64 {
	return atomic.LoadUint64(&failureCount)
}

func GetSuccessRate() float64 {
	total := atomic.LoadUint64(&requestCount)
	if total == 0 {
		return 100.0
	}
	success := atomic.LoadUint64(&successCount)
	return float64(success) / float64(total) * 100
}

func GetUptime() time.Duration {
	return time.Since(startTime)
}

func ResetMetrics() {
	atomic.StoreUint64(&requestCount, 0)
	atomic.StoreUint64(&successCount, 0)
	atomic.StoreUint64(&failureCount, 0)
}

var (
	httpRequestsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "hjtpx_http_requests_total",
			Help: "Total number of HTTP requests",
		},
		[]string{"method", "endpoint", "status_code"},
	)

	httpRequestDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "hjtpx_http_request_duration_seconds",
			Help:    "HTTP request duration in seconds",
			Buckets: []float64{.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10},
		},
		[]string{"method", "endpoint"},
	)

	httpRequestSize = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "hjtpx_http_request_size_bytes",
			Help:    "HTTP request size in bytes",
			Buckets: prometheus.ExponentialBuckets(100, 2, 10),
		},
		[]string{"method", "endpoint"},
	)

	httpResponseSize = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "hjtpx_http_response_size_bytes",
			Help:    "HTTP response size in bytes",
			Buckets: prometheus.ExponentialBuckets(100, 2, 10),
		},
		[]string{"method", "endpoint"},
	)

	httpActiveRequests = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Name: "hjtpx_http_active_requests",
			Help: "Number of active HTTP requests",
		},
	)

	dbConnectionsTotal = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Name: "hjtpx_db_connections_total",
			Help: "Total database connections",
		},
	)

	dbConnectionsActive = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Name: "hjtpx_db_connections_active",
			Help: "Number of active database connections",
		},
	)

	dbConnectionsIdle = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Name: "hjtpx_db_connections_idle",
			Help: "Number of idle database connections",
		},
	)

	dbWaitCount = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "hjtpx_db_wait_count_total",
			Help: "Total number of waits for a database connection",
		},
	)

	dbWaitDuration = prometheus.NewHistogram(
		prometheus.HistogramOpts{
			Name:    "hjtpx_db_wait_duration_seconds",
			Help:    "Duration of waits for database connections",
			Buckets: []float64{.001, .005, .01, .05, .1, .5, 1, 5},
		},
	)

	dbQueryDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "hjtpx_db_query_duration_seconds",
			Help:    "Database query duration",
			Buckets: []float64{.001, .005, .01, .05, .1, .5, 1, 5, 10},
		},
		[]string{"query_type"},
	)

	dbSlowQueries = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "hjtpx_db_slow_queries_total",
			Help: "Total number of slow queries",
		},
		[]string{"query_type"},
	)

	cacheHits = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "hjtpx_cache_hits_total",
			Help: "Total number of cache hits",
		},
	)

	cacheMisses = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "hjtpx_cache_misses_total",
			Help: "Total number of cache misses",
		},
	)

	cacheSize = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Name: "hjtpx_cache_keys_total",
			Help: "Total number of cache keys",
		},
	)

	uptime = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Name: "hjtpx_uptime_seconds",
			Help: "Application uptime in seconds",
		},
	)

	version = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Name: "hjtpx_version",
			Help: "Application version",
		},
	)

	captchaGeneratedTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "hjtpx_captcha_generated_total",
			Help: "Total number of captcha generated by type",
		},
		[]string{"captcha_type"},
	)

	captchaVerifiedTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "hjtpx_captcha_verified_total",
			Help: "Total number of captcha verified by type and result",
		},
		[]string{"captcha_type", "result"},
	)

	captchaVerifyDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "hjtpx_captcha_verify_duration_seconds",
			Help:    "Captcha verification duration",
			Buckets: []float64{.001, .005, .01, .05, .1, .5, 1, 5},
		},
		[]string{"captcha_type"},
	)

	captchaBlockedTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "hjtpx_captcha_blocked_total",
			Help: "Total number of blocked captcha attempts",
		},
		[]string{"reason"},
	)

	captchaActiveCount = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "hjtpx_captcha_active_count",
			Help: "Number of active captchas",
		},
		[]string{"captcha_type"},
	)

	securityBlockedTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "hjtpx_security_blocked_total",
			Help: "Total number of blocked requests by security middleware",
		},
		[]string{"middleware", "reason"},
	)

	securityRiskScore = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "hjtpx_security_risk_score",
			Help:    "Distribution of risk scores",
			Buckets: []float64{0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100},
		},
		[]string{"request_type"},
	)

	authAttemptsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "hjtpx_auth_attempts_total",
			Help: "Total number of authentication attempts",
		},
		[]string{"result"},
	)

	mfaAttemptsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "hjtpx_mfa_attempts_total",
			Help: "Total number of MFA attempts",
		},
		[]string{"method", "result"},
	)

	rateLimitHitsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "hjtpx_rate_limit_hits_total",
			Help: "Total number of rate limit hits",
		},
		[]string{"type", "limit_type"},
	)

	blacklistHitsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "hjtpx_blacklist_hits_total",
			Help: "Total number of blacklist hits",
		},
		[]string{"type"},
	)

	websocketConnections = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Name: "hjtpx_websocket_connections_active",
			Help: "Number of active WebSocket connections",
		},
	)

	websocketMessagesTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "hjtpx_websocket_messages_total",
			Help: "Total number of WebSocket messages",
		},
		[]string{"direction", "message_type"},
	)

	applicationRequestsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "hjtpx_application_requests_total",
			Help: "Total number of requests per application",
		},
		[]string{"app_id", "endpoint"},
	)

	applicationLatency = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "hjtpx_application_latency_seconds",
			Help:    "Application endpoint latency",
			Buckets: []float64{.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5},
		},
		[]string{"app_id", "endpoint"},
	)

	botDetectionTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "hjtpx_bot_detection_total",
			Help: "Total number of bot detections",
		},
		[]string{"detection_type", "action"},
	)

	traceAnalysisDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "hjtpx_trace_analysis_duration_seconds",
			Help:    "Trace analysis duration",
			Buckets: []float64{.001, .005, .01, .05, .1, .5, 1, 5},
		},
		[]string{"analysis_type"},
	)

	fingerprintAnalysisDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "hjtpx_fingerprint_analysis_duration_seconds",
			Help:    "Fingerprint analysis duration",
			Buckets: []float64{.001, .005, .01, .05, .1, .5},
		},
		[]string{"component"},
	)

	proxyDetectionTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "hjtpx_proxy_detection_total",
			Help: "Total number of proxy/VPN detections",
		},
		[]string{"detection_type"},
	)

	environmentDetectionTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "hjtpx_environment_detection_total",
			Help: "Total number of environment detections",
		},
		[]string{"environment_type", "result"},
	)
)

func init() {
	prometheus.MustRegister(
		httpRequestsTotal,
		httpRequestDuration,
		httpRequestSize,
		httpResponseSize,
		httpActiveRequests,
		dbConnectionsTotal,
		dbConnectionsActive,
		dbConnectionsIdle,
		dbWaitCount,
		dbWaitDuration,
		dbQueryDuration,
		dbSlowQueries,
		cacheHits,
		cacheMisses,
		cacheSize,
		uptime,
		version,
		captchaGeneratedTotal,
		captchaVerifiedTotal,
		captchaVerifyDuration,
		captchaBlockedTotal,
		captchaActiveCount,
		securityBlockedTotal,
		securityRiskScore,
		authAttemptsTotal,
		mfaAttemptsTotal,
		rateLimitHitsTotal,
		blacklistHitsTotal,
		websocketConnections,
		websocketMessagesTotal,
		applicationRequestsTotal,
		applicationLatency,
		botDetectionTotal,
		traceAnalysisDuration,
		fingerprintAnalysisDuration,
		proxyDetectionTotal,
		environmentDetectionTotal,
	)

	version.Set(1.0)

	go updateUptime()
	go updateDBMetrics()
}

func updateUptime() {
	ticker := time.NewTicker(1 * time.Second)
	defer ticker.Stop()

	for range ticker.C {
		uptime.Set(time.Since(startTime).Seconds())
	}
}

func updateDBMetrics() {
	ticker := time.NewTicker(10 * time.Second)
	defer ticker.Stop()

	for range ticker.C {
		metrics, err := database.GetConnectionPoolMetrics()
		if err != nil {
			continue
		}

		dbConnectionsTotal.Set(float64(metrics.TotalConnections))
		dbConnectionsActive.Set(float64(metrics.ActiveConnections))
		dbConnectionsIdle.Set(float64(metrics.IdleConnections))
		dbWaitCount.Add(float64(metrics.WaitCount))
		dbWaitDuration.Observe(metrics.WaitDuration.Seconds())
	}
}

func PrometheusMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		start := time.Now()
		httpActiveRequests.Inc()

		defer func() {
			httpActiveRequests.Dec()

			duration := time.Since(start).Seconds()
			statusCode := strconv.Itoa(c.Writer.Status())
			endpoint := c.FullPath()
			if endpoint == "" {
				endpoint = c.Request.URL.Path
			}

			httpRequestsTotal.WithLabelValues(c.Request.Method, endpoint, statusCode).Inc()
			httpRequestDuration.WithLabelValues(c.Request.Method, endpoint).Observe(duration)
			httpRequestSize.WithLabelValues(c.Request.Method, endpoint).Observe(float64(c.Request.ContentLength))
			httpResponseSize.WithLabelValues(c.Request.Method, endpoint).Observe(float64(c.Writer.Size()))
		}()

		c.Next()
	}
}

func RegisterMetricsEndpoint(r *gin.Engine) {
	r.GET("/metrics", func(c *gin.Context) {
		promhttp.Handler().ServeHTTP(c.Writer, c.Request)
	})
	log.Println("Prometheus metrics endpoint registered at /metrics")
}

func RecordCacheHit() {
	cacheHits.Inc()
}

func RecordCacheMiss() {
	cacheMisses.Inc()
}

func RecordCacheSize(size int64) {
	cacheSize.Set(float64(size))
}

func RecordDBQueryDuration(queryType string, duration time.Duration) {
	dbQueryDuration.WithLabelValues(queryType).Observe(duration.Seconds())
	if duration.Seconds() > 1.0 {
		dbSlowQueries.WithLabelValues(queryType).Inc()
	}
}

func RecordCaptchaGenerated(captchaType string) {
	captchaGeneratedTotal.WithLabelValues(captchaType).Inc()
}

func RecordCaptchaVerified(captchaType string, success bool) {
	result := "success"
	if !success {
		result = "failure"
	}
	captchaVerifiedTotal.WithLabelValues(captchaType, result).Inc()
}

func RecordCaptchaVerifyDuration(captchaType string, duration time.Duration) {
	captchaVerifyDuration.WithLabelValues(captchaType).Observe(duration.Seconds())
}

func RecordCaptchaBlocked(captchaType string) {
	captchaBlockedTotal.WithLabelValues(captchaType).Inc()
}

func SetCaptchaActiveCount(captchaType string, count int64) {
	captchaActiveCount.WithLabelValues(captchaType).Set(float64(count))
}

func RecordSecurityBlocked(middleware, reason string) {
	securityBlockedTotal.WithLabelValues(middleware, reason).Inc()
}

func RecordSecurityRiskScore(requestType string, score float64) {
	securityRiskScore.WithLabelValues(requestType).Observe(score)
}

func RecordAuthAttempt(success bool) {
	result := "success"
	if !success {
		result = "failure"
	}
	authAttemptsTotal.WithLabelValues(result).Inc()
}

func RecordMFAAttempt(method string, success bool) {
	result := "success"
	if !success {
		result = "failure"
	}
	mfaAttemptsTotal.WithLabelValues(method, result).Inc()
}

func RecordRateLimitHit(rateLimitType, limitType string) {
	rateLimitHitsTotal.WithLabelValues(rateLimitType, limitType).Inc()
}

func RecordBlacklistHit(blacklistType string) {
	blacklistHitsTotal.WithLabelValues(blacklistType).Inc()
}

func SetWebSocketConnections(count int64) {
	websocketConnections.Set(float64(count))
}

func RecordWebSocketMessage(direction, messageType string) {
	websocketMessagesTotal.WithLabelValues(direction, messageType).Inc()
}

func RecordApplicationRequest(appID, endpoint string) {
	applicationRequestsTotal.WithLabelValues(appID, endpoint).Inc()
}

func RecordApplicationLatency(appID, endpoint string, duration time.Duration) {
	applicationLatency.WithLabelValues(appID, endpoint).Observe(duration.Seconds())
}

func RecordBotDetection(detectionType, action string) {
	botDetectionTotal.WithLabelValues(detectionType, action).Inc()
}

func RecordTraceAnalysisDuration(analysisType string, duration time.Duration) {
	traceAnalysisDuration.WithLabelValues(analysisType).Observe(duration.Seconds())
}

func RecordFingerprintAnalysisDuration(component string, duration time.Duration) {
	fingerprintAnalysisDuration.WithLabelValues(component).Observe(duration.Seconds())
}

func RecordProxyDetection(detectionType string) {
	proxyDetectionTotal.WithLabelValues(detectionType).Inc()
}

func RecordEnvironmentDetection(envType string, isSuspicious bool) {
	result := "normal"
	if isSuspicious {
		result = "suspicious"
	}
	environmentDetectionTotal.WithLabelValues(envType, result).Inc()
}

func GetMetricsSummary() map[string]interface{} {
	return map[string]interface{}{
		"http_requests_total": GetRequestCount(),
		"http_success_rate":   GetSuccessRate(),
		"uptime_seconds":      GetUptime().Seconds(),
	}
}

func Handler() http.Handler {
	return promhttp.Handler()
}
