apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hjtpx.fullname" . }}-config
  labels:
    {{- include "hjtpx.labels" . | nindent 4 }}
data:
  GIN_MODE: {{ .Values.config.GIN_MODE | quote }}
  SERVER_PORT: {{ .Values.config.SERVER_PORT | quote }}
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}
  LOG_FORMAT: {{ .Values.config.LOG_FORMAT | quote }}
  TZ: {{ .Values.config.TZ | quote }}
