apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hjtpx.fullname" . }}-secrets
  labels:
    {{- include "hjtpx.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | default (randAlphaNum 32) }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | default (randAlphaNum 16) }}
  REDIS_PASSWORD: {{ .Values.secrets.REDIS_PASSWORD | default "" | quote }}
