apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hjtpx

resources:
  - ../base

patches:
  - path: resources-patch.yaml
    target:
      kind: Deployment
      name: hjtpx

images:
  - name: ghcr.io/hjtpx/hjtpx
    newTag: v1.0.0
