apiVersion: apps/v1
kind: Deployment
metadata:
  name: hjtpx
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: hjtpx
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
