apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hjtpx

resources:
  - 00-namespace.yaml
  - 01-config.yaml
  - 02-postgres.yaml
  - 03-redis.yaml
  - 04-app.yaml
  - 05-ingress.yaml
  - 06-monitoring.yaml

commonLabels:
  app.kubernetes.io/name: hjtpx

configMapGenerator:
  - name: hjtpx-config
    behavior: replace
    literals:
      - GIN_MODE=release

images:
  - name: ghcr.io/hjtpx/hjtpx
    newName: ghcr.io/hjtpx/hjtpx
    newTag: latest
