apiVersion: apps/v1
kind: Deployment
metadata:
  name: hjtpx
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: hjtpx
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
